PLUGIN = {}
PLUGIN.name = "mise-env-sample"
PLUGIN.version = "0.0.1"
PLUGIN.homepage = "https://github.com/jfk9w/mise-ssh-crypt"
PLUGIN.license = "MIT"
PLUGIN.description = "Loads secrets using ssh-crypt"
PLUGIN.minRuntimeVersion = "0.3.0"
PLUGIN.manifestUrl = "https://github.com/jfk9w/mise-ssh-crypt/releases/download/manifest/manifest.json"
PLUGIN.notes = {}
